[package]
name = "rpiapptmon"
version = "0.1.0"
authors = ["greg"]
edition = "2018"

[dependencies]
i2cdev = "0.4.1"
chrono = "0.4.6"
reqwest = "0.9.20"
serde_json = "1.0.40"
serde = "1.0.99"
rppal = "0.11.3"
jsonrpc = "0.11.0"